### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pmatseykanets** [laravel-notification-channels/hipchat#6]
- [x] Add support for file sharing.
- [x] Add Card support in HipChatMessage for reacher notifications
- [ ] Consider adding support for User private messages in addition to room notifications
